config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#home"
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :organizations do
    resources :memberships
    resources :boards do
      resources :lists do
        resources :cards
      end
    end
  end

  resources :messages, only: [ :index, :create ]

  resources :cards, only: [] do
    member do
      patch :update_position
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :organization
  has_many :lists, dependent: :destroy
  has_many :cards, through: :lists, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organization
  before_action :set_board, only: [ :show, :edit, :update, :destroy ]

  def index
    @boards = @organization.boards
  end

  def show
    @lists = @board.lists.where.not(id: nil)
  end

  def new
    @board = @organization.boards.build
  end

  def create
    @organization = Organization.find(params[:organization_id])
    @board = @organization.boards.build(board_params)

    if @board.save
      @board.lists.create(name: "To-Do")
      redirect_to organization_board_path(@organization, @board), notice: "Board was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to organization_board_path(@organization, @board), notice: "Board was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to organization_boards_path(@organization), notice: "Board was successfully destroyed."
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  def board_params
    params.require(:board).permit(:name, :description, :visibility)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<div class="container w-1/4 mt-4 mx-auto">
  <h2 class="mb-4 text-2xl font-semibold">Edit Board</h2>
  <%= form_with model: [@organization, @board], class: "needs-validation", novalidate: true do |f| %>
    <div class="flex flex-col mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control rounded-md focus:border-secondary focus:ring-secondary", required: true %>
    </div>
    <div class="flex flex-col mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control rounded-md focus:border-secondary focus:ring-secondary", rows: 3 %>
    </div>
    <%= f.submit "Update Board", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/boards/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Boards#index</h1>
  <p>Find me in app/views/boards/index.html.erb</p>
</div>

app/views/boards/new.html.erb
<div class="container w-1/4 mt-4 mx-auto">
  <h2 class="mb-4 text-2xl font-semibold">Create New Board</h2>
  <%= form_with model: [@organization, @board], class: "needs-validation", novalidate: true do |f| %>
    <div class="flex flex-col mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control rounded-md focus:border-secondary focus:ring-secondary", required: true %>
    </div>
    <div class="flex flex-col mb-3">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control rounded-md focus:border-secondary focus:ring-secondary", rows: 3 %>
    </div>
    <%= f.submit "Create Board", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/boards/show.html.erb
<%# INSIDE THE LIST ITSELF %>
<div class="flex flex-col space-y-4 mx-10">
  <div class="text-3xl font-bold border-b-2 border-gray-300 pb-2">
    <%= link_to "#{@board.organization.name}", organization_path(@board.organization), class: "" %>
  </div>

  <div class="flex justify-between items-center w-full">
        <div class="flex flex-col space-y-2">
          <div class="flex items-center space-x-2">
            <h1 class="text-2xl font-semibold mr-3"><%= @board.name %></h1>
          <%= link_to image_tag("edit_icon.svg", width: 21, height: 21, title: "Edit"), edit_organization_board_path(@board.organization, @board), class: "" %>
          <%= link_to image_tag("trash_icon.svg", width: 21, height: 21, title: "Delete"), organization_board_path(@board.organization, @board), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this board?" }, class: "" %>
        </div>
        <p class="text-gray-600"><%= @board.description %></p>
        </div>
    <div class="">
      <%= form_with model: [@board.organization, @board, @board.lists.build], local: true, class: "flex items-center space-x-2" do |f| %>
        <%= f.text_field :name, placeholder: "List name", class: "form-input rounded-md" %>
        <%= f.submit "Create List", class: "btn" %>
      <% end %>
    </div>
  </div>

  <div class="flex space-x-4 overflow-x-auto" data-controller="card">
    <% @lists.each do |list| %>
      <div class="bg-gray-100 p-4 rounded-lg min-w-[250px] max-w-[350px]">
        <div class="flex justify-between items-center mb-2">
          <h3 class="font-semibold"><%= list.name %></h3>
          <div class="flex space-x-3">
            <button data-action="click->card#toggleCardForm" data-list-id="<%= list.id %>" class="">
              <%= image_tag "plus_icon.svg", width: 15, height: 15 %>
            </button>
            <%= link_to image_tag("trash_icon.svg", width: 18, height: 18), organization_board_list_path(@board.organization, @board, list),
                method: :delete,
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" },
                class: "" %>
          </div>
        </div>

        <div id="cardForm<%= list.id %>" class="hidden mb-4" data-card-target="cardForm">
          <%= form_with(
            model: [list, list.cards.build],
            url: organization_board_list_cards_path(@board.organization, @board, list),
            local: true,
            class: "space-y-2"
          ) do |f| %>
            <%= f.hidden_field :list_id, value: list.id %>
            <%= f.text_field :title, placeholder: "Card title", class: "form-input w-full" %>
            <%= f.text_area :description, placeholder: "Description", class: "form-textarea w-full" %>
            <%= f.datetime_field :due_date, class: "form-input w-full" %>
            <%= f.collection_select :assigned_user_id, User.all, :id, :email, { prompt: "Assign to user" }, class: "form-select w-full" %>
            <%= f.submit "Create Card", class: "cursor-pointer w-full hover:text-tertiary" %>
          <% end %>
        </div>

        <div class="space-y-2 card-list" data-list-id="<%= list.id %>">
          <% list.cards.order(:position).each do |card| %>
            <div class="card bg-white p-2 rounded shadow cursor-pointer" data-card-id="<%= card.id %>" data-action="click->card#toggleCardDetails">
              <div class="card-summary">
                <h4 class="font-semibold"><%= card.title %></h4>
                <p class="text-sm text-gray-600" data-card-target="truncatedDescription"><%= truncate(card.description, length: 35) %></p>
              </div>
              <div id="card-details-<%= card.id %>" class="card-details hidden space-y-2" data-card-target="cardDetails">
                <p class="text-sm text-gray-600 hidden" data-card-target="fullDescription"><%= card.description %></p>
                <p class="text-xs text-gray-500">Due: <%= card.due_date&.strftime("%Y-%m-%d %H:%M") %></p>
                <div class="flex justify-between items-center">
                <p class="text-xs text-gray-500">Assigned to: <%= card.assigned_user&.email %></p>

                  <%= link_to image_tag("trash_icon.svg", width: 18, height: 18), organization_board_list_card_path(@board.organization, @board, list, card), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this card?" }, class: "text-xs" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>