config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#home"
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :organizations do
    resources :memberships
    resources :boards do
      resources :lists do
        resources :cards
      end
    end
  end

  resources :messages, only: [ :index, :create ]

  resources :cards, only: [] do
    member do
      patch :update_position
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :boards, dependent: :destroy

  accepts_nested_attributes_for :memberships, reject_if: :all_blank

  after_create :add_owner_as_member

  private

  def add_owner_as_member
    memberships.create(user: owner, role: 'admin') unless memberships.exists?(user: owner)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organization, only: [ :show, :edit, :update, :destroy ]

  def index
    @organizations = current_user.all_organizations
  end

  def show
    # @organization = Organization.includes(boards: :lists).find(params[:id])
    # @organizations = current_user.organizations.includes(boards: :lists)
  end

  def new
    @organization = Organization.new
    @organization.memberships.build
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.owner = current_user


    if @organization.save
      redirect_to @organization, notice: "Organization was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update(organization_params)
      redirect_to organization_path(@organization), notice: "Organization was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path, notice: "Organization was successfully destroyed."
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name, :description, memberships_attributes: [ :user_id, :role ])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/index.html.erb
<div class="mx-10">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl my-5">My Projects</h1>
    <%= link_to "New", new_organization_path, class: "bg-tertiary text-white hover:bg-secondary hover:text-tertiary hover:scale-110 transition duration-300 ease-in-out font-semibold py-2 px-4 rounded" %>
  </div>

  <% if @organizations.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <% @organizations.each do |organization| %>
        <div class="bg-white shadow-md rounded-lg p-4 hover:shadow-lg transition-shadow duration-300">
          <%= link_to organization_path(organization), class: "block" do %>
            <h2 class="text-xl font-semibold text-gray-800 hover:text-tertiary"><%= organization.name %></h2>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="text-center text-gray-600 mt-20">
      <p>No projects created yet.<br>Add your first project and see it displayed here</p>
    </div>
  <% end %>
</div>

app/views/organizations/new.html.erb
<div class="flex items-center justify-center my-10 ">
  <div class="p-4 w-1/2 max-w-md rounded-lg" style="box-shadow: 0 0 15px 5px #f19992;">
    <h2 class="text-xl text-center font-bold mb-4">Create Project</h2>

    <%= form_with model: @organization, local: true, class: "space-y-4" do |f| %>
      <div class="field">
        <%= f.label :name, class: "block font-light mb-1" %>
        <%= f.text_field :name, class: "w-full bg-transparent border border-gray-600 rounded-md p-2 focus:border-white focus:outline-none focus:ring-1 focus:ring-white" %>
      </div>

      <div class="field">
        <%= f.label :description, class: "block font-light mb-1" %>
        <%= f.text_area :description, class: "w-full bg-transparent border border-gray-600 rounded-md p-2 focus:border-white focus:outline-none focus:ring-1 focus:ring-white" %>
      </div>

      <%# <h3 class="text-lg font-semibold mt-4 mb-2">Invite User</h3> %>
      <%= f.fields_for :memberships, @organization.memberships.build do |m| %>
        <div class="field">
          <%= m.label :user_id, "Invite Members", class: "block font-light mb-1" %>
          <%= m.collection_select :user_id, User.all, :id, :email, { prompt: "Select a user" }, { class: "w-full bg-transparent border border-gray-600 rounded-md p-2 focus:border-white focus:outline-none focus:ring-1 focus:ring-white" } %>
        </div>

        <div class="field">
          <%= m.label :role, class: "block font-light mb-1" %>
          <%= m.select :role, Membership.roles.keys.map { |role| [role.humanize, role] }, { prompt: "Select a role" }, { class: "w-full bg-transparent border border-gray-600 rounded-md p-2 focus:border-white focus:outline-none focus:ring-1 focus:ring-white" } %>
        </div>
      <% end %>

      <div class="actions flex justify-center">
        <%= f.submit "Create Project and Invite User", class: "w-full bg-tertiary text-white hover:bg-secondary hover:text-tertiary transition duration-300 ease-in-out font-semibold py-2 px-4 rounded" %>
      </div>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="flex flex-col mx-10" data-controller="invite-form">
  <div class="flex space-x-10 items-center">
    <div class="flex flex-col w-2/3">
      <h1 class="font-bold text-2xl"><%= @organization.name %></h1>
      <p class="text-gray-600 my-2"><%= @organization.description %></p>
    </div>
    <div class="my-5">
      <div class="flex items-center">
        <h2 class="font-bold text-lg mr-2 text-start">Members</h2>
        <button data-action="click->invite-form#toggleForm" class=" hover:text-tertiary">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>
      <div class="flex -space-x-4 rtl:space-x-reverse">
        <% @organization.memberships.includes(:user).each_with_index do |membership, index| %>
          <% if index < 3 %>
            <% if membership.user.photo.attached? %>
              <%= image_tag membership.user.photo, class: "w-10 h-10 border-2 border-white rounded-full dark:border-gray-800" %>
            <% else %>
              <div class="relative w-10 h-10 overflow-hidden bg-gray-100 border-2 border-white rounded-full dark:border-gray-800">
                <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <% if @organization.memberships.count > 3 %>
          <a class="flex items-center justify-center w-10 h-10 text-xs font-medium text-white bg-gray-700 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800" href="#">
            +<%= @organization.memberships.count - 3 %>
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div id="inviteUserForm" data-invite-form-target="form" class="hidden my-5">
    <div class="flex">
      <%= form_with url: organization_memberships_path(@organization), local: true, data: { action: "submit->invite-form#hideForm" } do |f| %>
        <%= f.label :user_id, "Invite Member", class: "block" %>
        <%= f.collection_select 'membership[user_id]', User.all, :id, :email,
            { prompt: "Select a user" },
            { class: "rounded-md focus:ring-tertiary focus:border-tertiary mr-2" } %>
        <%= f.label :role, class: "block" %>
        <%= f.select 'membership[role]', Membership.roles.keys.map { |role| [role.humanize, role] },
            { prompt: "Select a role" },
            { class: "rounded-md focus:ring-tertiary focus:border-tertiary mr-2" } %>
        <%= f.submit "Invite User", class: "btn" %>
      <% end %>
    </div>
  </div>


  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const tabButtons = document.querySelectorAll('[role="tab"]');
      const tabContents = document.querySelectorAll('[role="tabpanel"]');

      tabButtons.forEach(button => {
        button.addEventListener('click', () => {
          const target = button.getAttribute('data-tabs-target');
          tabContents.forEach(content => {
            content.classList.add('hidden');
          });
          document.querySelector(target).classList.remove('hidden');

          tabButtons.forEach(btn => {
            btn.classList.remove('active');
            btn.setAttribute('aria-selected', 'false');
          });
          button.classList.add('active');
          button.setAttribute('aria-selected', 'true');
        });
      });
    });
  </script>

  <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
    <ul class="flex flex-wrap -mb-px text-sm font-medium text-center justify-between items-center" id="default-styled-tab" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-tertiary hover:text-tertiary dark:text-purple-500 dark:hover:text-tertriary border-tertiary dark:border-tertiary hover:border-tertiary" data-tabs-inactive-classes="dark:border-transparent text-gray-500 hover:text-gray-600 dark:text-gray-400 border-gray-100 hover:border-gray-300 dark:border-gray-700 dark:hover:text-gray-300" role="tablist">
      <div class="flex">
        <% @organization.boards.each_with_index do |board, index| %>
          <li class="me-2" role="presentation">
            <button class="inline-block p-4 border-b-2 rounded-t-lg <%= 'active' if index == 0 %>"
                    id="board-<%= board.id %>-tab"
                    data-tabs-target="#board-<%= board.id %>-content"
                    type="button"
                    role="tab"
                    aria-controls="board-<%= board.id %>"
                    aria-selected="<%= index == 0 %>">
              <%= board.name %>
            </button>
          </li>
        <% end %>
      </div>
      <%= link_to "Add a Board", new_organization_board_path(@organization), class: "text-center text-sm bg-gray-300 px-2 py-1 rounded-md w-32 mb-2" %>
    </ul>
  </div>
  <div id="default-styled-tab-content" class="mb-20">
    <% @organization.boards.each_with_index do |board, index| %>
      <div class="<%= 'hidden' unless index == 0 %> p-4 rounded-lg bg-gray-50 dark:bg-gray-800"
           id="board-<%= board.id %>-content"
           role="tabpanel"
           aria-labelledby="board-<%= board.id %>-tab">
        <%= render 'shared/board', board: board, lists: board.lists.where.not(id: nil) %>
      </div>
    <% end %>
  </div>
</div>